### PR TITLE
Update code to es6, added rollup and babel

### PR DESCRIPTION
**Pull request by gunins**
Hi, I rewrite md5 to es6, added rollup and babel also. 
Now is clean es6 file es6 UMD and es5 files.

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution, @gunins 
I've decided to leave the current master branch as is, but I've added your fork as link to the wiki:
https://github.com/blueimp/JavaScript-MD5/wiki

**Comment by stormasm** [comment]
@blueimp Would it be possible for you to put a link in your top level Readme.md to the es6 version as well...  Most people will not see it buried down in the wiki.  Another approach you could possibly do, is have an es6 branch for a while in your repo too...  And then in the future merge the branch into your master.  Just my 2 cents...  The way I found the es6 version was on NPM, otherwise I would have never known it existed.

**Comment by blueimp** [comment]
The reason I put those links in the Wiki is simply that it does not require a commit to the repo.

**Comment by stormasm** [comment]
@blueimp ---- yes, makes total sense, I understand...  If you remember, and its appropriate the next time you do make a commit to the repo, whenever that is in the future, it might make sense to also add it in to the Readme...

**Pull request closed without merging**
